--- #YAML:1.0
name:               WordPress-Plugin-WallFlower
version:            0.0.3
abstract:           Holding Dance Floor Walls up since 20120810174359 Pacific Time.
author:
    - C.J. Adams-Collier <cjac@colliertech.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Test::More:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
